apiVersion: v1
kind: PersistentVolume
metadata:
  name: d-2zecbf8g28s44ampj7cx
  labels:
    alicloud-pvname: d-2zecbf8g28s44ampj7cx
    failure-domain.beta.kubernetes.io/zone: cn-beijing-g
    failure-domain.beta.kubernetes.io/region: cn-beijing
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "alicloud/disk"
    fsType: "ext4"
    options:
      volumeId: "d-2zecbf8g28s44ampj7cx"
  persistentVolumeReclaimPolicy: Delete
  storageClassName: alicloud-disk-efficiency
